// Autogenerated by Thrift Compiler (0.9.2)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package feature

import (
	"fmt"
	"github.com/apache/thrift/lib/go/thrift"
)

func GetImgFeature(image []byte, hostport string) (features []float64, err error) {
	//trans
	var trans thrift.TTransport
	trans, err = thrift.NewTSocket(hostport)
	if err != nil {
		return features, fmt.Errorf("Error creating transport %v", err)
	}
	defer trans.Close()
	//protocol
	var protocolFactory thrift.TProtocolFactory
	protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()

	//client
	client := NewFeatureClientFactory(trans, protocolFactory)
	if err := trans.Open(); err != nil {
		return features, fmt.Errorf("Error opening socket to %s, %v ", hostport, err)
	}
	fmt.Println("len of image is", len(image))
	features, err = client.Feature(image)
	if err != nil {
		return features, fmt.Errorf("Error client.Feature(image) %v", err)
	}
	fmt.Println("feature vector of image is", features)
	return features, nil
}
